services:
  - type: web
    name: healthledger-fl
    runtime: node
    plan: free # Change to starter if you need more memory for training
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set manually using your Neon Connection String
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: "*" # Or your Render URL once deployed
      # Required Blockchain Env Vars
      - key: POLYGON_AMOY_RPC
        sync: false # Set manually in Render Dashboard (e.g. Alchemy/Infura URL)
      - key: PRIVATE_KEY
        sync: false # Set manually in Render Dashboard
      - key: CONTRACT_ADDRESS
        sync: false # Set manually in Render Dashboard (0x90C51BB9EbA91F1A8D3215539CF15BbA7aeE6d11)
      - key: PINATA_API_KEY
        sync: false # Set manually in Render Dashboard
      - key: PINATA_SECRET
        sync: false # Set manually in Render Dashboard
    autoDeploy: true
